// Generated by Installer/build-installer.sh (make release). Do not edit by hand.
export const release = {
  version: '0.6.0' as string | null,
  fileName: 'Sona-0.6.0.pkg',
  downloadUrl: '/downloads/Sona-0.6.0.pkg' as string | null,
  sha256: '735d9f8dce1b481855cefddf376a5b8be5c7ae530915cb09d151b5fcd4810429',
  sizeBytes: 1862333,
  releasedAt: '2026-09-20',
  notarized: false,
  minMacOS: '26',
  sourceUrl: null as string | null,
};
